### ISSUE TITLE
lowercase folder name causes error

### ISSUE THREAD

**Issue by shahabgheysari** [niyiomotoso/the-guardian-api-php-client#6]
I got the below error 
![gaurdian](https://github.com/niyiomotoso/the-guardian-api-php-client/assets/15012793/88fdd5d5-bd4a-4488-abce-c97d74667986)
  
it is raised because of the lowercase folder name (src/config/Urls.php) that mismatches with the namespace (use Guardian\Config\Urls;). it mostly happens on the Linux OSs as they are case-sensitive.

**Comment by Kingdageek** [comment]
Hey,
thanks for mentioning this! It's fixed now. Pardon the late response too, didn't see the GitHub notification
